### PR TITLE
1.15.x compatibility (tested & working) :)

### PR DESCRIPTION
**Pull request by Aurelien30000**

### CODE REVIEW

**Comment by Aurelien30000** [comment]
For interested people, here is my PR built ;)

[InventoryRollback-1.3.7.zip](https://github.com/danjono/Inventory-Rollback/files/4060687/InventoryRollback-1.3.7.zip)

**Comment by B-Knight49** [comment]
Using the above, the plugin just stopped working after 1 restart (if that). It doesn't respond to any commands, there's absolutely no errors in console, it's not breaking or disabling, just entering anything returns nothing at all. If I had to hazard a guess, it's probably an issue with some of the saves from our players have broken it somehow.

**Comment by Aurelien30000** [comment]
> EDIT: Seems like it completely breaks regardless, even having removed the config and having downloaded 1.3.6. Running /ir [anything] does absolutely nothing. No errors, not disabling, no messages, absolutely nothing. Like it were never even a thing.

Why do yoi comment on my PR if you use 1.3.6 🤔 Unless you try to use IR on 1.15, I can't really help you, check your logs and check that the plugin is enabled and functionnal :) @B-Knight49

**Comment by B-Knight49** [comment]
It's on 1.15.
I used your PR before I used 1.3.6.
I edited my comment.

I actually realised that it's not breaking, it's just the lack of any feedback in the chat. I'm tempted to submit a PR myself to fix that since not entering the commands exactly just gives you nothing. I was entering /ir rollback rather than /ir restore and it returned nothing when it should've said the usage. 

Sorry for the comment, I believed it was your PR. It wasn't.

**Comment by Aurelien30000** [comment]
> It's on 1.15.
> I used your PR before I used 1.3.6.
> I edited my comment.
> 
> I actually realised that it's not breaking, it's just the lack of any feedback in the chat. I'm tempted to submit a PR myself to fix that since not entering the commands exactly just gives you nothing. I was entering /ir rollback rather than /ir restore and it returned nothing when it should've said the usage.
> 
> Sorry for the comment, I believed it was your PR. It wasn't.

Oh okay ! Don't worry, and I'll try to make another PR to add what you expect with commands, would be indeed interesting ! :)

**Pull request merged**
