### PR TITLE
1.16.2 support & some improvements

### PR DESCRIPTION
**Pull request by Aurelien30000**

### CODE REVIEW

**Comment by Aurelien30000** [comment]
[InventoryRollback-1.3.9.zip](https://github.com/danjono/Inventory-Rollback/files/5070018/InventoryRollback-1.3.9.zip)

**Comment by Aurelien30000** [comment]
Test build [InventoryRollback-1.4.0.zip](https://github.com/danjono/Inventory-Rollback/files/5070069/InventoryRollback-1.4.0.zip)

**Comment by Doc94** [comment]
Hi, maybe can add for 1.16.3 (?
only patchs.

**Comment by Aurelien30000** [comment]
@Doc94 1.16.3 is already compatible :)

**Pull request merged**
